"""Initial migration

Revision ID: 722f2d1b6442
Revises: 
Create Date: 2026-02-08 11:22:52.899604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722f2d1b6442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_id'), 'emotion', ['id'], unique=False)
    op.create_index(op.f('ix_emotion_name'), 'emotion', ['name'], unique=True)
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_id'), 'persona', ['id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('thought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('action_orientation', sa.String(), nullable=True),
    sa.Column('thought_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_id'), 'thought', ['id'], unique=False)
    op.create_table('thought_emotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thought_id', sa.Integer(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotion.id'], ),
    sa.ForeignKeyConstraint(['thought_id'], ['thought.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_emotion_id'), 'thought_emotion', ['id'], unique=False)
    op.create_table('thought_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['thought.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['thought.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_link_id'), 'thought_link', ['id'], unique=False)
    op.create_table('thought_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thought_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['thought_id'], ['thought.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_tag_id'), 'thought_tag', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thought_tag_id'), table_name='thought_tag')
    op.drop_table('thought_tag')
    op.drop_index(op.f('ix_thought_link_id'), table_name='thought_link')
    op.drop_table('thought_link')
    op.drop_index(op.f('ix_thought_emotion_id'), table_name='thought_emotion')
    op.drop_table('thought_emotion')
    op.drop_index(op.f('ix_thought_id'), table_name='thought')
    op.drop_table('thought')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_persona_id'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_emotion_name'), table_name='emotion')
    op.drop_index(op.f('ix_emotion_id'), table_name='emotion')
    op.drop_table('emotion')
    # ### end Alembic commands ###
