"""Add topics

Revision ID: 9eca8bb5a11d
Revises: 722f2d1b6442
Create Date: 2026-02-14 20:02:46.440884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eca8bb5a11d'
down_revision: Union[str, None] = '722f2d1b6442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_id'), 'topic', ['id'], unique=False)
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=True)
    op.create_table('thought_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thought_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['thought_id'], ['thought.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_topic_id'), 'thought_topic', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thought_topic_id'), table_name='thought_topic')
    op.drop_table('thought_topic')
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_index(op.f('ix_topic_id'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
