"""Initial migration

Revision ID: dbf1ae7bdd99
Revises: 
Create Date: 2026-02-05 19:11:55.354118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbf1ae7bdd99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thought_emotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thought_id', sa.Integer(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotion.id'], ),
    sa.ForeignKeyConstraint(['thought_id'], ['thought.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_emotion_id'), 'thought_emotion', ['id'], unique=False)
    op.create_table('thought_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['thought.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['thought.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_link_id'), 'thought_link', ['id'], unique=False)
    op.create_table('thought_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thought_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['thought_id'], ['thought.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thought_tag_id'), 'thought_tag', ['id'], unique=False)
    op.drop_index(op.f('thoughtlink_source_id'), table_name='thoughtlink')
    op.drop_index(op.f('thoughtlink_source_id_target_id'), table_name='thoughtlink')
    op.drop_index(op.f('thoughtlink_target_id'), table_name='thoughtlink')
    op.drop_table('thoughtlink')
    op.drop_index(op.f('thoughttag_tag_id'), table_name='thoughttag')
    op.drop_index(op.f('thoughttag_thought_id'), table_name='thoughttag')
    op.drop_table('thoughttag')
    op.drop_index(op.f('thoughtemotion_emotion_id'), table_name='thoughtemotion')
    op.drop_index(op.f('thoughtemotion_thought_id'), table_name='thoughtemotion')
    op.drop_table('thoughtemotion')
    op.alter_column('emotion', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('emotion_name'), table_name='emotion')
    op.create_index(op.f('ix_emotion_id'), 'emotion', ['id'], unique=False)
    op.create_index(op.f('ix_emotion_name'), 'emotion', ['name'], unique=True)
    op.alter_column('persona', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('persona', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('persona', 'gender',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_persona_id'), 'persona', ['id'], unique=False)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('tag_name'), table_name='tag')
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.alter_column('thought', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('thought', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('thought', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('thought', 'is_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('thought', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('thought', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_index(op.f('thought_persona_id'), table_name='thought')
    op.create_index(op.f('ix_thought_id'), 'thought', ['id'], unique=False)
    op.create_foreign_key(None, 'thought', 'persona', ['persona_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thought', type_='foreignkey')
    op.drop_index(op.f('ix_thought_id'), table_name='thought')
    op.create_index(op.f('thought_persona_id'), 'thought', ['persona_id'], unique=False)
    op.alter_column('thought', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('thought', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('thought', 'is_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('thought', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('thought', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('thought', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.create_index(op.f('tag_name'), 'tag', ['name'], unique=True)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_persona_id'), table_name='persona')
    op.alter_column('persona', 'gender',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('persona', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('persona', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_emotion_name'), table_name='emotion')
    op.drop_index(op.f('ix_emotion_id'), table_name='emotion')
    op.create_index(op.f('emotion_name'), 'emotion', ['name'], unique=True)
    op.alter_column('emotion', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('thoughtemotion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thought_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emotion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_generated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotion.id'], name=op.f('thoughtemotion_emotion_id_fkey')),
    sa.ForeignKeyConstraint(['thought_id'], ['thought.id'], name=op.f('thoughtemotion_thought_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('thoughtemotion_pkey'))
    )
    op.create_index(op.f('thoughtemotion_thought_id'), 'thoughtemotion', ['thought_id'], unique=False)
    op.create_index(op.f('thoughtemotion_emotion_id'), 'thoughtemotion', ['emotion_id'], unique=False)
    op.create_table('thoughttag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thought_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_generated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('thoughttag_tag_id_fkey')),
    sa.ForeignKeyConstraint(['thought_id'], ['thought.id'], name=op.f('thoughttag_thought_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('thoughttag_pkey'))
    )
    op.create_index(op.f('thoughttag_thought_id'), 'thoughttag', ['thought_id'], unique=False)
    op.create_index(op.f('thoughttag_tag_id'), 'thoughttag', ['tag_id'], unique=False)
    op.create_table('thoughtlink',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['thought.id'], name=op.f('thoughtlink_source_id_fkey')),
    sa.ForeignKeyConstraint(['target_id'], ['thought.id'], name=op.f('thoughtlink_target_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('thoughtlink_pkey'))
    )
    op.create_index(op.f('thoughtlink_target_id'), 'thoughtlink', ['target_id'], unique=False)
    op.create_index(op.f('thoughtlink_source_id_target_id'), 'thoughtlink', ['source_id', 'target_id'], unique=True)
    op.create_index(op.f('thoughtlink_source_id'), 'thoughtlink', ['source_id'], unique=False)
    op.drop_index(op.f('ix_thought_tag_id'), table_name='thought_tag')
    op.drop_table('thought_tag')
    op.drop_index(op.f('ix_thought_link_id'), table_name='thought_link')
    op.drop_table('thought_link')
    op.drop_index(op.f('ix_thought_emotion_id'), table_name='thought_emotion')
    op.drop_table('thought_emotion')
    # ### end Alembic commands ###
