"""Add profile to Persona

Revision ID: ded767c43319
Revises: 9eca8bb5a11d
Create Date: 2026-02-14 20:20:15.558262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded767c43319'
down_revision: Union[str, None] = '9eca8bb5a11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'profile')
    # ### end Alembic commands ###
